// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: complex.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugins       []*Plugin              `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginList) Reset() {
	*x = PluginList{}
	mi := &file_complex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginList) ProtoMessage() {}

func (x *PluginList) ProtoReflect() protoreflect.Message {
	mi := &file_complex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginList.ProtoReflect.Descriptor instead.
func (*PluginList) Descriptor() ([]byte, []int) {
	return file_complex_proto_rawDescGZIP(), []int{0}
}

func (x *PluginList) GetPlugins() []*Plugin {
	if x != nil {
		return x.Plugins
	}
	return nil
}

type Plugin struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ManufacturerId string                 `protobuf:"bytes,2,opt,name=manufacturer_id,json=manufacturerId,proto3" json:"manufacturer_id,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Subtype        string                 `protobuf:"bytes,4,opt,name=subtype,proto3" json:"subtype,omitempty"`
	Parameters     []*Parameter           `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Plugin) Reset() {
	*x = Plugin{}
	mi := &file_complex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plugin) ProtoMessage() {}

func (x *Plugin) ProtoReflect() protoreflect.Message {
	mi := &file_complex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plugin.ProtoReflect.Descriptor instead.
func (*Plugin) Descriptor() ([]byte, []int) {
	return file_complex_proto_rawDescGZIP(), []int{1}
}

func (x *Plugin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Plugin) GetManufacturerId() string {
	if x != nil {
		return x.ManufacturerId
	}
	return ""
}

func (x *Plugin) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Plugin) GetSubtype() string {
	if x != nil {
		return x.Subtype
	}
	return ""
}

func (x *Plugin) GetParameters() []*Parameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type Parameter struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DisplayName         string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	DefaultValue        float32                `protobuf:"fixed32,2,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	CurrentValue        float32                `protobuf:"fixed32,3,opt,name=current_value,json=currentValue,proto3" json:"current_value,omitempty"`
	Address             int32                  `protobuf:"varint,4,opt,name=address,proto3" json:"address,omitempty"`
	MaxValue            float32                `protobuf:"fixed32,5,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	MinValue            float32                `protobuf:"fixed32,6,opt,name=min_value,json=minValue,proto3" json:"min_value,omitempty"`
	Unit                string                 `protobuf:"bytes,7,opt,name=unit,proto3" json:"unit,omitempty"`
	Identifier          string                 `protobuf:"bytes,8,opt,name=identifier,proto3" json:"identifier,omitempty"`
	CanRamp             bool                   `protobuf:"varint,9,opt,name=can_ramp,json=canRamp,proto3" json:"can_ramp,omitempty"`
	IsWritable          bool                   `protobuf:"varint,10,opt,name=is_writable,json=isWritable,proto3" json:"is_writable,omitempty"`
	RawFlags            int64                  `protobuf:"varint,11,opt,name=raw_flags,json=rawFlags,proto3" json:"raw_flags,omitempty"`
	IndexedValues       *IndexedValues         `protobuf:"bytes,12,opt,name=indexed_values,json=indexedValues,proto3,oneof" json:"indexed_values,omitempty"`
	IndexedValuesSource *string                `protobuf:"bytes,13,opt,name=indexed_values_source,json=indexedValuesSource,proto3,oneof" json:"indexed_values_source,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Parameter) Reset() {
	*x = Parameter{}
	mi := &file_complex_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameter) ProtoMessage() {}

func (x *Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_complex_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameter.ProtoReflect.Descriptor instead.
func (*Parameter) Descriptor() ([]byte, []int) {
	return file_complex_proto_rawDescGZIP(), []int{2}
}

func (x *Parameter) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Parameter) GetDefaultValue() float32 {
	if x != nil {
		return x.DefaultValue
	}
	return 0
}

func (x *Parameter) GetCurrentValue() float32 {
	if x != nil {
		return x.CurrentValue
	}
	return 0
}

func (x *Parameter) GetAddress() int32 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *Parameter) GetMaxValue() float32 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

func (x *Parameter) GetMinValue() float32 {
	if x != nil {
		return x.MinValue
	}
	return 0
}

func (x *Parameter) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Parameter) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *Parameter) GetCanRamp() bool {
	if x != nil {
		return x.CanRamp
	}
	return false
}

func (x *Parameter) GetIsWritable() bool {
	if x != nil {
		return x.IsWritable
	}
	return false
}

func (x *Parameter) GetRawFlags() int64 {
	if x != nil {
		return x.RawFlags
	}
	return 0
}

func (x *Parameter) GetIndexedValues() *IndexedValues {
	if x != nil {
		return x.IndexedValues
	}
	return nil
}

func (x *Parameter) GetIndexedValuesSource() string {
	if x != nil && x.IndexedValuesSource != nil {
		return *x.IndexedValuesSource
	}
	return ""
}

type IndexedValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexedValues) Reset() {
	*x = IndexedValues{}
	mi := &file_complex_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexedValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexedValues) ProtoMessage() {}

func (x *IndexedValues) ProtoReflect() protoreflect.Message {
	mi := &file_complex_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexedValues.ProtoReflect.Descriptor instead.
func (*IndexedValues) Descriptor() ([]byte, []int) {
	return file_complex_proto_rawDescGZIP(), []int{3}
}

func (x *IndexedValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_complex_proto protoreflect.FileDescriptor

const file_complex_proto_rawDesc = "" +
	"\n" +
	"\rcomplex.proto\x12\x04test\"4\n" +
	"\n" +
	"PluginList\x12&\n" +
	"\aplugins\x18\x01 \x03(\v2\f.test.PluginR\aplugins\"\xa4\x01\n" +
	"\x06Plugin\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0fmanufacturer_id\x18\x02 \x01(\tR\x0emanufacturerId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\asubtype\x18\x04 \x01(\tR\asubtype\x12/\n" +
	"\n" +
	"parameters\x18\x05 \x03(\v2\x0f.test.ParameterR\n" +
	"parameters\"\x80\x04\n" +
	"\tParameter\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12#\n" +
	"\rdefault_value\x18\x02 \x01(\x02R\fdefaultValue\x12#\n" +
	"\rcurrent_value\x18\x03 \x01(\x02R\fcurrentValue\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\x05R\aaddress\x12\x1b\n" +
	"\tmax_value\x18\x05 \x01(\x02R\bmaxValue\x12\x1b\n" +
	"\tmin_value\x18\x06 \x01(\x02R\bminValue\x12\x12\n" +
	"\x04unit\x18\a \x01(\tR\x04unit\x12\x1e\n" +
	"\n" +
	"identifier\x18\b \x01(\tR\n" +
	"identifier\x12\x19\n" +
	"\bcan_ramp\x18\t \x01(\bR\acanRamp\x12\x1f\n" +
	"\vis_writable\x18\n" +
	" \x01(\bR\n" +
	"isWritable\x12\x1b\n" +
	"\traw_flags\x18\v \x01(\x03R\brawFlags\x12?\n" +
	"\x0eindexed_values\x18\f \x01(\v2\x13.test.IndexedValuesH\x00R\rindexedValues\x88\x01\x01\x127\n" +
	"\x15indexed_values_source\x18\r \x01(\tH\x01R\x13indexedValuesSource\x88\x01\x01B\x11\n" +
	"\x0f_indexed_valuesB\x18\n" +
	"\x16_indexed_values_source\"'\n" +
	"\rIndexedValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06valuesB\x06Z\x04./pbb\x06proto3"

var (
	file_complex_proto_rawDescOnce sync.Once
	file_complex_proto_rawDescData []byte
)

func file_complex_proto_rawDescGZIP() []byte {
	file_complex_proto_rawDescOnce.Do(func() {
		file_complex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_complex_proto_rawDesc), len(file_complex_proto_rawDesc)))
	})
	return file_complex_proto_rawDescData
}

var file_complex_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_complex_proto_goTypes = []any{
	(*PluginList)(nil),    // 0: test.PluginList
	(*Plugin)(nil),        // 1: test.Plugin
	(*Parameter)(nil),     // 2: test.Parameter
	(*IndexedValues)(nil), // 3: test.IndexedValues
}
var file_complex_proto_depIdxs = []int32{
	1, // 0: test.PluginList.plugins:type_name -> test.Plugin
	2, // 1: test.Plugin.parameters:type_name -> test.Parameter
	3, // 2: test.Parameter.indexed_values:type_name -> test.IndexedValues
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_complex_proto_init() }
func file_complex_proto_init() {
	if File_complex_proto != nil {
		return
	}
	file_complex_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_complex_proto_rawDesc), len(file_complex_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_complex_proto_goTypes,
		DependencyIndexes: file_complex_proto_depIdxs,
		MessageInfos:      file_complex_proto_msgTypes,
	}.Build()
	File_complex_proto = out.File
	file_complex_proto_goTypes = nil
	file_complex_proto_depIdxs = nil
}
