package igniffi

import "strings"

// GenerateTypesHeader generates igniffi_types.h with core type definitions
func GenerateTypesHeader() string {
	var b strings.Builder

	b.WriteString(`// Code generated by ffire - DO NOT EDIT
// igniffi - Micro ffire C API
// Core type definitions

#ifndef IGNIFFI_TYPES_H
#define IGNIFFI_TYPES_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

// ============================================================================
// String View (zero-copy, no null terminator required)
// ============================================================================

typedef struct {
    const char* data;
    size_t size;
} igniffi_StringView;

// Helper to create StringView from C string (computes strlen)
static inline igniffi_StringView igniffi_stringview(const char* str) {
    igniffi_StringView sv;
    sv.data = str;
    sv.size = str ? strlen(str) : 0;
    return sv;
}

// Helper to create StringView from buffer with known size
static inline igniffi_StringView igniffi_stringview_n(const char* data, size_t size) {
    igniffi_StringView sv;
    sv.data = data;
    sv.size = size;
    return sv;
}

// Compare two StringViews for equality
static inline bool igniffi_stringview_eq(igniffi_StringView a, igniffi_StringView b) {
    return a.size == b.size && (a.size == 0 || memcmp(a.data, b.data, a.size) == 0);
}

// ============================================================================
// Status / Error Handling
// ============================================================================

typedef struct {
    bool ok;
    const char* message;  // Borrowed string, valid until next operation
} igniffi_Status;

// Helper to create success status
static inline igniffi_Status igniffi_ok(void) {
    igniffi_Status status;
    status.ok = true;
    status.message = NULL;
    return status;
}

// Helper to create error status
static inline igniffi_Status igniffi_error(const char* msg) {
    igniffi_Status status;
    status.ok = false;
    status.message = msg;
    return status;
}

// ============================================================================
// Arena Statistics (for debugging)
// ============================================================================

typedef struct {
    size_t bytes_allocated;
    size_t num_blocks;
} igniffi_ArenaStats;

#ifdef __cplusplus
}
#endif

#endif // IGNIFFI_TYPES_H
`)

	return b.String()
}
