// Code generated by ffire. DO NOT EDIT.

#ifndef TEST_C_H
#define TEST_C_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>
#include <stdint.h>

// Opaque handle types
typedef void* ConfigHandle;
typedef void* ConfigHandle;

// Decode function
ConfigHandle config_decode(const uint8_t* data, size_t len, char** error_msg);

// Encode function
size_t config_encode(ConfigHandle handle, uint8_t** out_data, char** error_msg);

// Memory management functions
void config_free(ConfigHandle handle);
void config_free_data(uint8_t* data);
void config_free_error(char* error_msg);

// Getter functions
const char* config_get_host(ConfigHandle handle);
int32_t config_get_port(ConfigHandle handle);
int config_get_enablessl(ConfigHandle handle);
float config_get_timeout(ConfigHandle handle);
int32_t config_get_maxretries(ConfigHandle handle);

#ifdef __cplusplus
}
#endif

#endif // TEST_C_H
