// Code generated by ffire. DO NOT EDIT.

#include <napi.h>
#include "include/generated.hpp"
#include <vector>
#include <string>

using namespace test;

// Decode ConfigMessage from Buffer to JS Object
Napi::Value DecodeConfigMessage(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();

  if (info.Length() < 1 || !info[0].IsBuffer()) {
    Napi::TypeError::New(env, "Buffer expected").ThrowAsJavaScriptException();
    return env.Null();
  }

  Napi::Buffer<uint8_t> buffer = info[0].As<Napi::Buffer<uint8_t>>();

  Config msg = decode_config_message(buffer.Data(), buffer.Length());

  Napi::Object obj = Napi::Object::New(env);
  obj.Set("Host", Napi::String::New(env, msg.Host));
  obj.Set("Port", Napi::Number::New(env, msg.Port));
  obj.Set("EnableSSL", Napi::Boolean::New(env, msg.EnableSSL));
  obj.Set("Timeout", Napi::Number::New(env, msg.Timeout));
  obj.Set("MaxRetries", Napi::Number::New(env, msg.MaxRetries));
  return obj;
}

// Encode ConfigMessage from JS Object to Buffer
Napi::Value EncodeConfigMessage(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();

  if (info.Length() < 1 || !info[0].IsObject()) {
    Napi::TypeError::New(env, "Object expected").ThrowAsJavaScriptException();
    return env.Null();
  }

  Napi::Object obj = info[0].As<Napi::Object>();

  Config msg;
  msg.Host = obj.Get("Host").As<Napi::String>().Utf8Value();
  msg.Port = obj.Get("Port").As<Napi::Number>().Int32Value();
  msg.EnableSSL = obj.Get("EnableSSL").As<Napi::Boolean>().Value();
  msg.Timeout = obj.Get("Timeout").As<Napi::Number>().FloatValue();
  msg.MaxRetries = obj.Get("MaxRetries").As<Napi::Number>().Int32Value();
  std::vector<uint8_t> encoded = encode_config_message(msg);

  return Napi::Buffer<uint8_t>::Copy(env, encoded.data(), encoded.size());
}

Napi::Object Init(Napi::Env env, Napi::Object exports) {
  exports.Set("encodeConfigMessage", Napi::Function::New(env, EncodeConfigMessage));
  exports.Set("decodeConfigMessage", Napi::Function::New(env, DecodeConfigMessage));
  return exports;
}

NODE_API_MODULE(test, Init)
