from setuptools import setup, find_packages
import platform

# Determine which library to include based on platform
data_files = []
system = platform.system()
if system == 'Darwin':
    data_files = ['test/libffire.dylib']
elif system == 'Linux':
    data_files = ['test/libffire.so']
elif system == 'Windows':
    data_files = ['test/ffire.dll']

setup(
    name='test',
    version='1.0.0',
    description='FFire binary serialization library - test schema',
    author='Generated by FFire',
    packages=find_packages(),
    package_data={
        'test': data_files,
    },
    python_requires='>=3.7',
    classifiers=[
        'Development Status :: 4 - Beta',
        'Intended Audience :: Developers',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
    ],
)
